name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - '27.1'
          - '27.2'
          - '28.1'
          - '28.2'
          - '29.1'
          - '29.2'
          - '29.3'
          - '29.4'
          - 'snapshot'
        include:
          - emacs_version: 'snapshot'
            allow_failure: true
    steps:
    - uses: actions/checkout@v4
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: actions/setup-python@v5
    - uses: conao3/setup-cask@master

    - name: Install dependencies
      run: 'cask install'

    - name: Run tests
      if: matrix.allow_failure != true
      run: |
        cask exec ert-runner --reporter ert+duration
        cask exec emacs --eval "(setq byte-compile-error-on-warn t)" -L . --batch -f batch-byte-compile smartparens.el smartparens-*[^pkg].el

    - name: Run tests (allow failure)
      if: matrix.allow_failure == true
      run: |
        cask exec ert-runner --reporter ert+duration || true
        cask exec emacs --eval "(setq byte-compile-error-on-warn t)" -L . --batch -f batch-byte-compile smartparens.el smartparens-*[^pkg].el || true
